// ============================================================================
// LabelMergeEngine.cs - Label Conflict Resolution and Merging
// 🌼 Pansy - Universal Disassembly Metadata Format
// ============================================================================

namespace Pansy.Core;

/// <summary>
/// Merges labels from multiple sources with priority-based conflict resolution.
/// Priority order (highest to lowest): User > HardwareRegister > InternetDatabase > AutoGenerated > PatternDetected.
/// </summary>
public class LabelMergeEngine {
	private readonly Dictionary<uint, MergedLabel> _labels = [];
	private readonly List<MergeConflict> _conflicts = [];

	/// <summary>
	/// All merged labels indexed by address.
	/// </summary>
	public IReadOnlyDictionary<uint, MergedLabel> Labels => _labels;

	/// <summary>
	/// All conflicts that occurred during merging.
	/// </summary>
	public IReadOnlyList<MergeConflict> Conflicts => _conflicts;

	/// <summary>
	/// Add a single label. If an existing label has lower or equal priority,
	/// it is replaced and a conflict is logged. Higher-priority existing labels are kept.
	/// </summary>
	public void Add(MergedLabel label) {
		if (_labels.TryGetValue(label.Address, out var existing)) {
			if (label.Source < existing.Source) {
				// New label has higher priority (lower enum value)
				_conflicts.Add(new MergeConflict(label.Address, label, existing));
				_labels[label.Address] = label;
			} else if (label.Source > existing.Source) {
				// Existing label has higher priority
				_conflicts.Add(new MergeConflict(label.Address, existing, label));
			} else {
				// Same priority — first one wins (stable merge)
				_conflicts.Add(new MergeConflict(label.Address, existing, label));
			}
		} else {
			_labels[label.Address] = label;
		}
	}

	/// <summary>
	/// Add multiple labels from a batch source.
	/// </summary>
	public void AddRange(IEnumerable<MergedLabel> labels) {
		foreach (var label in labels) {
			Add(label);
		}
	}

	/// <summary>
	/// Add labels from a PansyLoader's existing symbols as User-sourced.
	/// </summary>
	public void AddUserSymbols(PansyLoader loader) {
		foreach (var kvp in loader.AllSymbolEntries) {
			foreach (var entry in kvp.Value) {
				Add(new MergedLabel(
					(uint)kvp.Key,
					entry.Name,
					entry.Type,
					LabelSource.User));
			}
		}
	}

	/// <summary>
	/// Add hardware register labels for a platform.
	/// </summary>
	public void AddHardwareRegisters(byte platformId) {
		var registers = PlatformDefaults.GetDefaultSymbolEntries(platformId);
		foreach (var (addr, symbol) in registers) {
			Add(new MergedLabel(
				addr,
				symbol.Name,
				symbol.Type,
				LabelSource.HardwareRegister,
				symbol.Description));
		}
	}

	/// <summary>
	/// Add auto-generated labels (from CDL analysis).
	/// </summary>
	public void AddAutoLabels(IEnumerable<(uint Address, string Name, SymbolType Type)> labels) {
		foreach (var (addr, name, type) in labels) {
			Add(new MergedLabel(addr, name, type, LabelSource.AutoGenerated));
		}
	}

	/// <summary>
	/// Add pattern-detected labels (str_, ptrtbl_, tiles_).
	/// </summary>
	public void AddPatternLabels(IEnumerable<(uint Address, string Name, SymbolType Type)> labels) {
		foreach (var (addr, name, type) in labels) {
			Add(new MergedLabel(addr, name, type, LabelSource.PatternDetected));
		}
	}

	/// <summary>
	/// Add internet/database-sourced labels.
	/// </summary>
	public void AddDatabaseLabels(IEnumerable<(uint Address, string Name, SymbolType Type, string? Description)> labels) {
		foreach (var (addr, name, type, desc) in labels) {
			Add(new MergedLabel(addr, name, type, LabelSource.InternetDatabase, desc));
		}
	}

	/// <summary>
	/// Get the final merged label set as symbol tuples for PansyWriter.AddSymbols().
	/// </summary>
	public IEnumerable<(uint Address, string Name, SymbolType Type)> GetMergedSymbols() {
		foreach (var (addr, label) in _labels) {
			yield return (addr, label.Name, label.Type);
		}
	}

	/// <summary>
	/// Get all conflicts where an auto-generated or pattern label was overridden.
	/// Useful for logging what the engine "would have named" an address.
	/// </summary>
	public IEnumerable<MergeConflict> GetOverriddenAutoLabels() {
		foreach (var conflict in _conflicts) {
			if (conflict.Loser.Source is LabelSource.AutoGenerated or LabelSource.PatternDetected) {
				yield return conflict;
			}
		}
	}

	/// <summary>
	/// Reset the engine, clearing all labels and conflicts.
	/// </summary>
	public void Clear() {
		_labels.Clear();
		_conflicts.Clear();
	}
}
