using System.Linq;
using Xunit;

namespace Pansy.Core.Tests;

public class LabelMergeEngineTests {
	// ========================================================================
	// Basic Add Operations
	// ========================================================================

	[Fact]
	public void Add_SingleLabel_StoredCorrectly() {
		var engine = new LabelMergeEngine();
		engine.Add(new MergedLabel(0x2000, "PPUCTRL", SymbolType.Constant, LabelSource.HardwareRegister));

		Assert.Single(engine.Labels);
		Assert.Equal("PPUCTRL", engine.Labels[0x2000].Name);
		Assert.Empty(engine.Conflicts);
	}

	[Fact]
	public void Add_DifferentAddresses_BothStored() {
		var engine = new LabelMergeEngine();
		engine.Add(new MergedLabel(0x10, "sub_0010", SymbolType.Function, LabelSource.AutoGenerated));
		engine.Add(new MergedLabel(0x20, "sub_0020", SymbolType.Function, LabelSource.AutoGenerated));

		Assert.Equal(2, engine.Labels.Count);
	}

	// ========================================================================
	// Priority Conflict Resolution
	// ========================================================================

	[Fact]
	public void Add_HigherPriorityOverridesLower() {
		var engine = new LabelMergeEngine();
		engine.Add(new MergedLabel(0x2000, "loc_2000", SymbolType.Label, LabelSource.AutoGenerated));
		engine.Add(new MergedLabel(0x2000, "PPUCTRL", SymbolType.Constant, LabelSource.HardwareRegister));

		Assert.Equal("PPUCTRL", engine.Labels[0x2000].Name);
		Assert.Single(engine.Conflicts);
		Assert.Equal("PPUCTRL", engine.Conflicts[0].Winner.Name);
		Assert.Equal("loc_2000", engine.Conflicts[0].Loser.Name);
	}

	[Fact]
	public void Add_LowerPriorityDoesNotOverride() {
		var engine = new LabelMergeEngine();
		engine.Add(new MergedLabel(0x2000, "PPUCTRL", SymbolType.Constant, LabelSource.HardwareRegister));
		engine.Add(new MergedLabel(0x2000, "loc_2000", SymbolType.Label, LabelSource.AutoGenerated));

		Assert.Equal("PPUCTRL", engine.Labels[0x2000].Name);
		Assert.Single(engine.Conflicts);
		Assert.Equal("PPUCTRL", engine.Conflicts[0].Winner.Name);
	}

	[Fact]
	public void Add_UserLabelNeverOverwritten() {
		var engine = new LabelMergeEngine();
		engine.Add(new MergedLabel(0x2000, "MyRegister", SymbolType.Label, LabelSource.User));
		engine.Add(new MergedLabel(0x2000, "PPUCTRL", SymbolType.Constant, LabelSource.HardwareRegister));
		engine.Add(new MergedLabel(0x2000, "loc_2000", SymbolType.Label, LabelSource.AutoGenerated));

		Assert.Equal("MyRegister", engine.Labels[0x2000].Name);
		Assert.Equal(2, engine.Conflicts.Count);
	}

	[Fact]
	public void Add_SamePriority_FirstOneWins() {
		var engine = new LabelMergeEngine();
		engine.Add(new MergedLabel(0x10, "sub_0010", SymbolType.Function, LabelSource.AutoGenerated));
		engine.Add(new MergedLabel(0x10, "loc_0010", SymbolType.Label, LabelSource.AutoGenerated));

		Assert.Equal("sub_0010", engine.Labels[0x10].Name);
		Assert.Single(engine.Conflicts);
	}

	[Theory]
	[InlineData(LabelSource.User, LabelSource.HardwareRegister)]
	[InlineData(LabelSource.User, LabelSource.AutoGenerated)]
	[InlineData(LabelSource.HardwareRegister, LabelSource.InternetDatabase)]
	[InlineData(LabelSource.HardwareRegister, LabelSource.AutoGenerated)]
	[InlineData(LabelSource.InternetDatabase, LabelSource.AutoGenerated)]
	[InlineData(LabelSource.AutoGenerated, LabelSource.PatternDetected)]
	public void Add_PriorityOrder_HigherAlwaysWins(LabelSource higher, LabelSource lower) {
		var engine = new LabelMergeEngine();
		engine.Add(new MergedLabel(0x100, "lower", SymbolType.Label, lower));
		engine.Add(new MergedLabel(0x100, "higher", SymbolType.Label, higher));

		Assert.Equal("higher", engine.Labels[0x100].Name);
	}

	// ========================================================================
	// Batch Operations
	// ========================================================================

	[Fact]
	public void AddRange_MultipleLables_AllAdded() {
		var engine = new LabelMergeEngine();
		var labels = new[] {
			new MergedLabel(0x10, "a", SymbolType.Label, LabelSource.AutoGenerated),
			new MergedLabel(0x20, "b", SymbolType.Label, LabelSource.AutoGenerated),
			new MergedLabel(0x30, "c", SymbolType.Label, LabelSource.AutoGenerated),
		};
		engine.AddRange(labels);

		Assert.Equal(3, engine.Labels.Count);
	}

	[Fact]
	public void AddUserSymbols_LoadsFromPansyLoader() {
		var writer = new PansyWriter {
			Platform = PansyLoader.PLATFORM_NES,
			RomSize = 256,
		};
		writer.AddSymbol(0x10, "MyFunc", SymbolType.Function);
		writer.AddSymbol(0x20, "MyData", SymbolType.Label);
		var data = writer.Generate();
		var loader = new PansyLoader(data);

		var engine = new LabelMergeEngine();
		engine.AddUserSymbols(loader);

		Assert.Equal(2, engine.Labels.Count);
		Assert.Equal("MyFunc", engine.Labels[0x10].Name);
		Assert.Equal(LabelSource.User, engine.Labels[0x10].Source);
	}

	[Fact]
	public void AddHardwareRegisters_LoadsNesRegisters() {
		var engine = new LabelMergeEngine();
		engine.AddHardwareRegisters(PansyLoader.PLATFORM_NES);

		Assert.True(engine.Labels.Count > 0);
		Assert.Equal("PPUCTRL", engine.Labels[0x2000].Name);
		Assert.Equal(LabelSource.HardwareRegister, engine.Labels[0x2000].Source);
	}

	[Fact]
	public void AddAutoLabels_SetsCorrectSource() {
		var engine = new LabelMergeEngine();
		engine.AddAutoLabels([(0x10u, "sub_0010", SymbolType.Function)]);

		Assert.Equal(LabelSource.AutoGenerated, engine.Labels[0x10].Source);
	}

	[Fact]
	public void AddPatternLabels_SetsCorrectSource() {
		var engine = new LabelMergeEngine();
		engine.AddPatternLabels([(0x80u, "str_000080", SymbolType.Label)]);

		Assert.Equal(LabelSource.PatternDetected, engine.Labels[0x80].Source);
	}

	[Fact]
	public void AddDatabaseLabels_SetsCorrectSource() {
		var engine = new LabelMergeEngine();
		engine.AddDatabaseLabels([(0x100u, "PlayerHP", SymbolType.Label, "Player health points")]);

		Assert.Equal(LabelSource.InternetDatabase, engine.Labels[0x100].Source);
		Assert.Equal("Player health points", engine.Labels[0x100].Description);
	}

	// ========================================================================
	// Full Merge Workflow
	// ========================================================================

	[Fact]
	public void FullMerge_UserOverridesAll() {
		var writer = new PansyWriter {
			Platform = PansyLoader.PLATFORM_NES,
			RomSize = 0x10000,
		};
		writer.AddSymbol(0x2000, "MyPPU", SymbolType.Label);
		writer.AddSymbol(0x10, "MyRoutine", SymbolType.Function);
		var data = writer.Generate();
		var loader = new PansyLoader(data);

		var engine = new LabelMergeEngine();

		// Add in reverse priority order — user should still win
		engine.AddPatternLabels([(0x2000u, "ptrtbl_002000", SymbolType.Label)]);
		engine.AddAutoLabels([(0x10u, "sub_0010", SymbolType.Function), (0x2000u, "loc_2000", SymbolType.Label)]);
		engine.AddHardwareRegisters(PansyLoader.PLATFORM_NES);
		engine.AddUserSymbols(loader);

		Assert.Equal("MyPPU", engine.Labels[0x2000].Name);
		Assert.Equal("MyRoutine", engine.Labels[0x10].Name);
	}

	[Fact]
	public void FullMerge_HwRegistersOverrideAutoLabels() {
		var engine = new LabelMergeEngine();

		engine.AddAutoLabels([(0x2000u, "loc_2000", SymbolType.Label)]);
		engine.AddHardwareRegisters(PansyLoader.PLATFORM_NES);

		Assert.Equal("PPUCTRL", engine.Labels[0x2000].Name);
	}

	// ========================================================================
	// GetMergedSymbols
	// ========================================================================

	[Fact]
	public void GetMergedSymbols_ReturnsAllLabels() {
		var engine = new LabelMergeEngine();
		engine.Add(new MergedLabel(0x10, "alpha", SymbolType.Label, LabelSource.User));
		engine.Add(new MergedLabel(0x20, "beta", SymbolType.Function, LabelSource.AutoGenerated));

		var symbols = engine.GetMergedSymbols().ToList();

		Assert.Equal(2, symbols.Count);
		Assert.Contains(symbols, s => s.Address == 0x10 && s.Name == "alpha");
		Assert.Contains(symbols, s => s.Address == 0x20 && s.Name == "beta");
	}

	// ========================================================================
	// Conflict Tracking
	// ========================================================================

	[Fact]
	public void GetOverriddenAutoLabels_FiltersCorrectly() {
		var engine = new LabelMergeEngine();
		engine.Add(new MergedLabel(0x10, "sub_0010", SymbolType.Function, LabelSource.AutoGenerated));
		engine.Add(new MergedLabel(0x10, "MainLoop", SymbolType.Function, LabelSource.User));
		engine.Add(new MergedLabel(0x20, "SomeDb", SymbolType.Label, LabelSource.InternetDatabase));
		engine.Add(new MergedLabel(0x20, "PPUCTRL", SymbolType.Constant, LabelSource.HardwareRegister));

		var overridden = engine.GetOverriddenAutoLabels().ToList();

		Assert.Single(overridden);
		Assert.Equal("sub_0010", overridden[0].Loser.Name);
	}

	// ========================================================================
	// Clear
	// ========================================================================

	[Fact]
	public void Clear_RemovesEverything() {
		var engine = new LabelMergeEngine();
		engine.Add(new MergedLabel(0x10, "test", SymbolType.Label, LabelSource.User));
		engine.Add(new MergedLabel(0x10, "test2", SymbolType.Label, LabelSource.AutoGenerated));

		engine.Clear();

		Assert.Empty(engine.Labels);
		Assert.Empty(engine.Conflicts);
	}

	// ========================================================================
	// Edge Cases
	// ========================================================================

	[Fact]
	public void Add_DescriptionPreservedOnWin() {
		var engine = new LabelMergeEngine();
		engine.Add(new MergedLabel(0x2000, "PPUCTRL", SymbolType.Constant,
			LabelSource.HardwareRegister, "PPU Control Register"));

		Assert.Equal("PPU Control Register", engine.Labels[0x2000].Description);
	}

	[Fact]
	public void Add_AddressZero_Works() {
		var engine = new LabelMergeEngine();
		engine.Add(new MergedLabel(0, "origin", SymbolType.Label, LabelSource.User));

		Assert.Single(engine.Labels);
		Assert.Equal("origin", engine.Labels[0].Name);
	}

	[Fact]
	public void FullMerge_NoConflicts_EmptyConflictList() {
		var engine = new LabelMergeEngine();
		engine.Add(new MergedLabel(0x10, "a", SymbolType.Label, LabelSource.User));
		engine.Add(new MergedLabel(0x20, "b", SymbolType.Label, LabelSource.HardwareRegister));
		engine.Add(new MergedLabel(0x30, "c", SymbolType.Label, LabelSource.AutoGenerated));

		Assert.Empty(engine.Conflicts);
	}
}
